### PR TITLE
Fix some outstanding issues

### LINKED ISSUE #2: README contains dead or stale links to vdr-developer.de
I was thoroughly confused by the following comment in the `README` file:
>Latest version available at: git://projects.vdr-developer.org/vdr-plugin-rpihddevice.git

That URL does work, but it has not been updated since 4744541fde542aa2193ffe6bdaa7c7762e7d1944. Furthermore:
>Project's homepage:          http://projects.vdr-developer.org/projects/plg-rpihddevice

Anything at http://projects.vdr-developer.org seems to currently return an internal error. I think that it did work some days or weeks ago.

### PR DESCRIPTION
**Pull request by dr-m**
I had already submitted the fixes to #1 and #4 as comments in the issues. Here they are in pull request form.

I was also able to fix the VDR shutdown problems on my system (#5).

All of these issues are a showstopper for me, and #1 seems to be a showstopper for many users. There exist fixes for it in the wild; see for example vdr-projects/vdr-plugin-rpihddevice@b527fe571ddb93c124fbdc323bef4313b9ba6c8f (which also fixes #2).

### CODE REVIEW

File: audio.c [hunk 1]
```diff
@@ -1293,7 +1294,7 @@ void cRpiAudioDecoder::Reset(void)
 	Lock();
 	m_reset = true;
 	m_wait->Signal();
-	while (m_reset)
+	while (m_reset && !m_terminated)
```
Comment (reufer) [inline audio.c]: Why not checking for cThread::Running() when entering the method?

File: omx.c [hunk 2]
```diff
@@ -590,7 +592,9 @@ int cOmx::DeInit(void)
 
 	OMX_Deinit();
 
+#if 0 // avoid a crash due to double free or heap corruption
 	ilclient_destroy(m_client);
```
Comment (reufer) [inline omx.c]: have you checked, whether there's no memory leak caused by this change?

File: audio.c (hunk 1 above)
Comment (dr-m) [reply audio.c]: I will try that once more. I think that I tried it and it did not prevent a hang.

File: omx.c (hunk 2 above)
Comment (dr-m) [reply omx.c]: I did not check it yet, but will do so. There is an occasional crash and a hang that occurs in `ilclient_teardown_tunnels()`. Here is the crash variant:
```
Thread 1 "vdr" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x76a1c480 (LWP 1236)]
0x763b6744 in vcil_out_ComponentTunnelRequest ()
   from /opt/vc/lib/libopenmaxil.so
(gdb) bt
#0  0x763b6744 in vcil_out_ComponentTunnelRequest ()
   from /opt/vc/lib/libopenmaxil.so
#1  0x764588c0 in OMX_SetupTunnel (hOutput=0x37d480, nPortOutput=190, 
    hInput=hInput@entry=0x0, nPortInput=nPortInput@entry=0) at ilcore.c:255
#2  0x76455224 in ilclient_teardown_tunnels (tunnel=tunnel@entry=0x2d8cc4)
    at ilclient.c:526
#3  0x7643f29c in cOmx::DeInit (this=0x2d8c70) at omx.c:588
#4  0x76442d3c in cOmxDevice::DeInit (this=0x2ddc70) at omxdevice.c:124
#5  0x76442ddc in cOmxDevice::~cOmxDevice (this=0x2ddc70, 
    __in_chrg=<optimized out>) at omxdevice.c:87
#6  0x76442e5c in cOmxDevice::~cOmxDevice (this=0x2ddc70, 
    __in_chrg=<optimized out>) at omxdevice.c:85
#7  0x00091144 in cDevice::Shutdown () at device.c:120
```

Comment (dr-m) [reply omx.c]: A build with `-fsanitize=address` would crash already on startup due to this:
```
==3183==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x73f57d60 at pc 0x76a5d548 bp 0x651fdba4 sp 0x651fd770
READ of size 20 at 0x73f57d60 thread T13 (ovgthread)
    #0 0x76a5d547  (/lib/arm-linux-gnueabihf/libasan.so.5+0x3a547)

0x73f57d60 is located 0 bytes to the right of 16-byte region [0x73f57d50,0x73f57d60)
allocated by thread T13 (ovgthread) here:
    #0 0x76b0662b in operator new(unsigned int) (/lib/arm-linux-gnueabihf/libasan.so.5+0xe362b)
    #1 0x74e6cb67 in __gnu_cxx::new_allocator<float>::allocate(unsigned int, void const*) /usr/include/c++/8/ext/new_allocator.h:111
    #2 0x74e6cb67 in std::allocator_traits<std::allocator<float> >::allocate(std::allocator<float>&, unsigned int) /usr/include/c++/8/bits/alloc_traits.h:436
    #3 0x74e6cb67 in std::_Vector_base<float, std::allocator<float> >::_M_allocate(unsigned int) /usr/include/c++/8/bits/stl_vector.h:296
    #4 0x74e6cb67 in void std::vector<float, std::allocator<float> >::_M_realloc_insert<float const&>(__gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >, float const&) /usr/include/c++/8/bits/vector.tcc:427

Thread T13 (ovgthread) created by T0 here:
    #0 0x76a6e9c7 in pthread_create (/lib/arm-linux-gnueabihf/libasan.so.5+0x4b9c7)
    #1 0x31cc27 in cThread::Start() /home/pi/vdr/thread.c:316
```
It may be that AddressSanitizer is not compatible with this library:
```
#6  0x74c925e8 in rpc_send_ctrl_write () from /opt/vc/lib/libbrcmEGL.so
#7  0x74ca29dc in vgDrawGlyphs () from /opt/vc/lib/libbrcmEGL.so
#8  0x74e75da0 in cOvgPaintBox::Draw (string=0x741203d0) at ovgosd.c:413
#9  cOvgCmdDrawText::Execute (this=<optimized out>, egl=<optimized out>) at ovgosd.c:1276
#10 0x74e695c8 in cOvgThread::Action (this=0x7432d080) at ovgosd.c:1902
#11 0x0031db6c in cThread::StartThread (Thread=0x7432d080) at thread.c:293
#12 0x769a4494 in start_thread (arg=0x651fe3c0) at pthread_create.c:486
#13 0x76605dd8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73
   from /lib/arm-linux-gnueabihf/libc.so.6
```
Can you suggest any other tools that could check for memory leaks? I have even less faith in Valgrind.

Comment (dr-m) [reply omx.c]: Actually, this could be a genuine buffer overflow for something that `cOvgThread` or `cOvgPaintBox` is responsible for. The general rule for AddressSanitizer is that any uninstrumented code (such as `libbrcmELG.so` here) is assumed to be valid. Some errors can still be caught even in uninstrumented code thanks to some page fault tricks.

I should have rerun it with `ASAN_OPTIONS=fast_unwind_on_malloc=0:abort_on_error=1` to get a full stack trace of the allocation. A consequence of any buffer overflow could be that the cleanup on shutdown hangs or crashes.

Looking at the code, the issue here might be that `string->Length()` is 0 and `vgDrawGlyphs()` would dereference the pointers to the non-existent 0th elements of the `std::vector` members in `cOvgString`.

I will try to get back to this within a few days.

Comment (dr-m) [reply omx.c]: The out-of-bounds access occurs for `m_kerning` while displaying the string `VDR`:
```
(gdb) p *string
$1 = {m_glyphIds = std::vector of length 3, capacity 4 = {86, 68, 82}, 
  m_kerning = std::vector of length 2, capacity 2 = {0, 0}, m_width = 2.375, 
  m_height = 1.1640625, m_descender = 0.23828125, m_font = 0x71b25cc0}
```
At the time of this crash, there was no visible change at the HDMI output yet.

Comment (dr-m) [reply omx.c]: To detect only memory leaks, we can suppress the detection of heap buffer overflows, heap-use-after-free and the like:
```sh
LD_PRELOAD=/lib/arm-linux-gnueabihf/libasan.so.5 \
ASAN_OPTIONS=poison_heap=0:fast_unwind_on_malloc=0 \
./vdr -L. --no-kbd --lirc=/dev/lirc0 -Prpihddevice -v /var/lib/vdr/video
```
I shut down the server by `telnet localhost 6419` and the following commands:
```
HITK setup
HITK right
HITK ok
HITK ok
```
Several memory leaks are reported. As far as I can tell, all can be attributed to  `rpihddevice` and not VDR 2.6.2 itself. Here is the list:
```
    #1 0x74c800b7 in cRpiAudioDecoder::cParser::Append(unsigned char const*, long long, unsigned int) /home/pi/vdr/PLUGINS/src/rpihddevice/audio.c:208
```
```c++
                        Pts* entry = new Pts(pts, length);
                        m_ptsQueue.push(entry);
```
The memory would be freed in `cRpiAudioDecoder::cParser::Reset()`, but maybe it was not called. It could make sense to store `Pts` directly by value in `m_ptsQueue`, because the values are small.
```
    #1 0x74cb767f in cOvgPixmap::DrawText(cPoint const&, char const*, unsigned int, unsigned int, cFont const*, int, int, int) /home/pi/vdr/PLUGINS/src/rpihddevice/ovgosd.c:2139
```
```c++
                unsigned int *symbols = MALLOC(unsigned int, len + 1);
```
This buffer is being passed to `cOvgCmdDrawText::cOvgCmdDrawText()`. Its destructor would call `free()`, but maybe the destructor itself is not being invoked. There is a `delete cmd` in `cOvgThread::Action()`, but apparently it will not always be called.

There were several occurrences of the second leak in this simple scenario.

No other memory leaks were reported, including any leaks for anything allocated in `cOmx`. The Broadcom libraries were not instrumented by AddressSanitizer, so any leaks there might remain undetected. Then again, Linux is supposed to free any resources, including any anonymous `mmap()` regions, when a process terminates.

File: audio.c (hunk 1 above)
Comment (dr-m) [reply audio.c]: You seem to be right, checking for `Running()` seems to suffice. Maybe last time I tried it, I had simply hit the hang in `cOmx::DeInit()`.

File: omx.c (hunk 2 above)
Comment (dr-m) [reply omx.c]: I ran eac8ef5f41f28630a2b136568833b7318c839b1f several times with
```sh
LD_PRELOAD=/lib/arm-linux-gnueabihf/libasan.so.5 ASAN_OPTIONS=poison_heap=0:abort_on_error=1:fast_unwind_on_malloc=0 ./vdr -L. --no-kbd --lirc=/dev/lirc0 -Prpihddevice -v /var/lib/vdr/video
```
and never got any memory leaks reported. However, before those invocations, I got some leaks reported for
```sh
LD_PRELOAD=/lib/arm-linux-gnueabihf/libasan.so.5 ASAN_OPTIONS=poison_heap=0 ./vdr -L. --no-kbd --lirc=/dev/lirc0 -Prpihddevice -v /var/lib/vdr/video
```
including some that could indeed be related to the disabled shutdown code:
```
Direct leak of 5304 byte(s) in 8 object(s) allocated from:
    #0 0x76a89bbb in __interceptor_malloc (/lib/arm-linux-gnueabihf/libasan.so.5+0xe1bbb)
    #1 0x74c16e9f in vcos_generic_mem_alloc_aligned /home/dom/projects/staging/userland/interface/vcos/generic/vcos_mem_from_malloc.c:56
```
These leak reports are reproducible. Somehow, `fast_unwind_on_malloc=0` makes the leaks disappear completely.

All that said, I believe that the leak that eac8ef5f41f28630a2b136568833b7318c839b1f fixes is much more grave, because it is about a recurring memory allocation. The OMX related memory allocations are only a one-time issue.

I would return to the memory leaks after AddressSanitizer no longer reports anything when `ASAN_OPTIONS` includes the default setting `poison_heap=1`. Maybe fixing the buffer overflows will also fix the crashes or hangs when the `#if 0` code is re-enabled.

Comment (dr-m) [reply omx.c]: The only source of heap buffer overflow on startup is `cOvgString::cOvgString()`, which is fixed in 4858804fd4c89b9be0feed4db8a00c716a9aee5c. I rebased the branch so that the somewhat controversial change (replacing a shutdown hang with potential memory leaks) is last (0ed99cc9c26da96a7d745ba15ba4a86b69ef0194).

It looks like when the plugin cleanup executes longer, then a heap-use-after-free has a better chance of occurring in the VDR 2.6.2 core. I am debugging this further.

Comment (dr-m) [reply omx.c]: The following patch fixes reduces the amount of observed heap-use-after-free on VDR 2.6.2 shutdown:
```diff
diff --git a/device.c b/device.c
index 4b9c9cc7..4e987389 100644
--- a/device.c
+++ b/device.c
@@ -125,7 +125,6 @@ cDevice::~cDevice()
   delete dvbSubtitleConverter;
   if (this == primaryDevice)
      primaryDevice = NULL;
-  Cancel(3);
 }
 
 bool cDevice::WaitForAllDevicesReady(int Timeout)
@@ -457,7 +456,10 @@ void cDevice::SetCamSlot(cCamSlot *CamSlot)
 void cDevice::Shutdown(void)
 {
   deviceHooks.Clear();
+  for (int i = 0; i < numDevices; i++)
+      device[i]->Cancel(-1);
   for (int i = 0; i < numDevices; i++) {
+      device[i]->Cancel(3);
       delete device[i];
       device[i] = NULL;
       }
```
Because AddressSanitizer slows down the shutdown and I got one more heap-use-after-free report with this patch present, I changed the delay to 30 seconds.

With this and only the following changes to `cOmx::Deinit()`:
```diff
diff --git a/omx.c b/omx.c
index 20f3e36..2e5e152 100644
--- a/omx.c
+++ b/omx.c
@@ -577,11 +577,13 @@ int cOmx::Init(int display, int layer)
 
 int cOmx::DeInit(void)
 {
-	Cancel(-1);
 	m_portEvents->Add(0);
+	Cancel(3);
 
+#if 0 // this would cause a hang on shutdown
 	for (int i = 0; i < eNumTunnels; i++)
 		ilclient_disable_tunnel(&m_tun[i]);
+#endif
 
 	ilclient_teardown_tunnels(m_tun);
 	ilclient_state_transition(m_comp, OMX_StateIdle);
```
shutdown under AddressSanitizer either hangs (in `OMX_Deinit()`, with only VCOS threads and the main thread existing) or reports a heap-use-after-free or double-free. Here is one example:
```
==4351==ERROR: AddressSanitizer: attempting double-free on 0x74379480 in thread T0:
    #0 0x76a51887 in __interceptor_free (/lib/arm-linux-gnueabihf/libasan.so.5+0xe1887)

0x74379480 is located 0 bytes inside of 2100-byte region [0x74379480,0x74379cb4)
freed by thread T0 here:
    #0 0x76a51887 in __interceptor_free (/lib/arm-linux-gnueabihf/libasan.so.5+0xe1887)
    #1 0x74cc200b in vcos_free /opt/vc/include/interface/vcos/generic/vcos_mem_from_malloc.h:63
    #2 0x74cc200b in ilclient_destroy /home/pi/vdr/PLUGINS/src/rpihddevice/ilclient/ilclient.c:196
    #3 0x74905617  (<unknown module>)
```
I will review https://github.com/raspberrypi/firmware/blob/master/opt/vc/src/hello_pi/hello_video/video.c and try to come up with better ideas. The current shutdown sequence looks similar to that code, but there could be race conditions outside the VCOS code.

Comment (dr-m) [reply omx.c]: Finally, 05bf186eb1606c741068737c7b3f49e8032d21b4 fixes the shutdown issues without removing any calls to the VideoCore interface.

Some leaks are still reported, but because they are not visible with `ASAN_OPTIONS=fast_unwind_on_malloc=0`, I cannot do anything about them:
```
==10878==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 7180 byte(s) in 9 object(s) allocated from:
    #0 0x76afa737 in __interceptor_posix_memalign (/lib/arm-linux-gnueabihf/libasan.so.5+0xe2737)
    #1 0x74a59677 in av_malloc (/lib/arm-linux-gnueabihf/neon/vfp/libavutil.so.56+0x2d677)

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x76af9bbb in __interceptor_malloc (/lib/arm-linux-gnueabihf/libasan.so.5+0xe1bbb)
    #1 0x7692a767  (/lib/arm-linux-gnueabihf/libfontconfig.so.1+0x1e767)

Indirect leak of 98144 byte(s) in 63 object(s) allocated from:
    #0 0x76afa737 in __interceptor_posix_memalign (/lib/arm-linux-gnueabihf/libasan.so.5+0xe2737)
    #1 0x74a59677 in av_malloc (/lib/arm-linux-gnueabihf/neon/vfp/libavutil.so.56+0x2d677)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x76af9d63 in calloc (/lib/arm-linux-gnueabihf/libasan.so.5+0xe1d63)
    #1 0x7692ad9b  (/lib/arm-linux-gnueabihf/libfontconfig.so.1+0x1ed9b)

Indirect leak of 8 byte(s) in 2 object(s) allocated from:
    #0 0x76af9f33 in realloc (/lib/arm-linux-gnueabihf/libasan.so.5+0xe1f33)
    #1 0x6ffdc1f3  (/lib/arm-linux-gnueabihf/neon/vfp/libavcodec.so.58+0x2651f3)

SUMMARY: AddressSanitizer: 105492 byte(s) leaked in 76 allocation(s).
```

**Comment by dr-m** [comment]
I tested 05bf186eb1606c741068737c7b3f49e8032d21b4 on VDR 2.6.2 with the following patch:
```diff
diff --git a/Makefile b/Makefile
index a251f903..e9f0c6f2 100644
--- a/Makefile
+++ b/Makefile
@@ -16,7 +16,7 @@ CC       ?= gcc
 CFLAGS   ?= -g -O3 -Wall
 
 CXX      ?= g++
-CXXFLAGS ?= -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses
+CXXFLAGS ?= -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fsanitize=address
 CXXFLAGS += $(CPPFLAGS)
 
 CDEFINES  = -D_GNU_SOURCE
diff --git a/device.c b/device.c
index 4b9c9cc7..c33e3297 100644
--- a/device.c
+++ b/device.c
@@ -125,7 +125,6 @@ cDevice::~cDevice()
   delete dvbSubtitleConverter;
   if (this == primaryDevice)
      primaryDevice = NULL;
-  Cancel(3);
 }
 
 bool cDevice::WaitForAllDevicesReady(int Timeout)
@@ -457,7 +456,10 @@ void cDevice::SetCamSlot(cCamSlot *CamSlot)
 void cDevice::Shutdown(void)
 {
   deviceHooks.Clear();
+  for (int i = 0; i < numDevices; i++)
+      device[i]->Cancel(-1);
   for (int i = 0; i < numDevices; i++) {
+      device[i]->Cancel(30);
       delete device[i];
       device[i] = NULL;
       }
diff --git a/dvbdevice.c b/dvbdevice.c
index 51331485..1caf1218 100644
--- a/dvbdevice.c
+++ b/dvbdevice.c
@@ -573,6 +573,7 @@ private:
   virtual void Action(void);
 public:
   cDvbTuner(const cDvbDevice *Device, int Adapter, int Frontend);
+  void Shutdown();
   virtual ~cDvbTuner();
   bool ProvidesDeliverySystem(int DeliverySystem) const;
   bool ProvidesModulation(int System, int StreamId, int Modulation) const;
@@ -648,12 +649,17 @@ cDvbTuner::cDvbTuner(const cDvbDevice *Device, int Adapter, int Frontend)
   Start();
 }
 
-cDvbTuner::~cDvbTuner()
+void cDvbTuner::Shutdown()
 {
   tunerStatus = tsIdle;
   newSet.Broadcast();
   locked.Broadcast();
   Cancel(3);
+}
+
+cDvbTuner::~cDvbTuner()
+{
+  Shutdown();
   UnBond();
   /* looks like this irritates the SCR switch, so let's leave it out for now
   if (lastDiseqc && lastDiseqc->IsScr()) {
@@ -1865,6 +1871,8 @@ cDvbDevice::cDvbDevice(int Adapter, int Frontend)
 
 cDvbDevice::~cDvbDevice()
 {
+  if (dvbTuner)
+     dvbTuner->Shutdown();
   StopSectionHandler();
   delete dvbTuner;
   delete ciAdapter;
```

File: audio.c (hunk 1 above)
Comment (dr-m) [reply audio.c]: Actually, checking for `Running()` is wrong, because it is only a request for the `Action()` to terminate. 05bf186eb1606c741068737c7b3f49e8032d21b4 checks for `cThread::Active()`.

**Review by reufer — APPROVED** [review]
Looks good to me - thanks a lot for your efforts!
